platform :ios, '15.0'

target 'ElizaCocoaPodsApp' do
  use_frameworks!

  # For real projects, use a version instead of a path:
  # pod 'Connect-Swift', '~> x.y.z'
  pod 'Connect-Swift', :path => '../..'
end
