name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {} # support manual runs
env:
  # Sets the Xcode version to use for the CI.
  # Available Versions: https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md#xcode
  # Ref: https://www.jessesquires.com/blog/2020/01/06/selecting-an-xcode-version-on-github-ci/
  DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer
permissions:
  contents: read
jobs:
  build-eliza-cocoapods-example:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Eliza CocoaPods example
        run: |
          cd Examples/ElizaCocoaPodsApp
          pod install
          set -o pipefail && xcodebuild -workspace ElizaCocoaPodsApp.xcworkspace -scheme ElizaCocoaPodsApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
  build-eliza-swiftpm-example:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Eliza Swift PM example
        run: |
          cd Examples/ElizaSwiftPackageApp
          set -o pipefail && xcodebuild -scheme ElizaSwiftPackageApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
  build-library-ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Connect iOS library
        run: set -o pipefail && xcodebuild -scheme Connect-Package -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' | xcbeautify
  build-library-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Connect macOS library
        run: set -o pipefail && xcodebuild -scheme Connect-Package -destination 'platform=macOS' | xcbeautify
  build-library-tvos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Connect tvOS library
        run: set -o pipefail && xcodebuild -scheme Connect-Package -destination 'platform=tvOS Simulator,name=Apple TV,OS=18.4' | xcbeautify
  build-library-watchos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Connect watchOS library
        run: set -o pipefail && xcodebuild -scheme Connect-Package -destination 'platform=watchOS Simulator,name=Apple Watch Series 10 (42mm),OS=11.0' | xcbeautify
  build-plugin-and-generate:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ github.token }}
      - name: Build plugins
        run: make buildplugins
      - name: Generate outputs
        run: make generate
      - name: Ensure no generated diff
        run: |
          git update-index --refresh --add --remove
          git diff-index --quiet HEAD --
  run-conformance-tests:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install conformance runner
        run: make installconformancerunner
      - name: Run conformance tests
        run: make testconformance
  run-unit-tests:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Run unit tests
        run: make testunit
  run-swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.58.2
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        run: swiftlint lint --strict
  validate-license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate license headers
        run: |
          make licenseheaders
          git update-index --refresh
          git diff-index --quiet HEAD --
